spring:
  application:
    name: mogu
  profiles:
    include: secret
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: always

  docker:
    compose:
      file: compose.yaml
      enabled: true
      lifecycle-management: none
      start:
        command: up
      stop:
        command: down
        timeout: 1m
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: -1

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
